Repository ra3xdh/qucs_s, pull requests merged in 2024-12, with the labels that each got.

#1123 inno setup improvements
  contrib/InnoSetup/qucs.iss
Labels: packaging, windows

#1112 AC power source amplitude fix
  qucs/components/source_ac.cpp
Labels: documentation

#1136 Add .CSPARAM Support
  qucs/bitmaps/svg/sp_csparam.svg
  qucs/components/componentdialog.cpp
  qucs/module.cpp
  qucs/qucs.qrc
  qucs/spicecomponents/CMakeLists.txt
  qucs/spicecomponents/sp_csparameter.cpp
  qucs/spicecomponents/sp_csparameter.h
  qucs/spicecomponents/spicecomponents.h
Labels: new feature

#1133 S-parameter Viewer: Some improvements
  qucs-s-spar-viewer/CMakeLists.txt
  qucs-s-spar-viewer/codeeditor.cpp
  qucs-s-spar-viewer/codeeditor.h
  qucs-s-spar-viewer/qucs-s-spar-viewer.cpp
  qucs-s-spar-viewer/qucs-s-spar-viewer.h
Labels: RF, tools
