Repository ra3xdh/qucs_s, pull requests merged in 2024-07, with the labels that each got.

#800 Add AppImage to continous release
  .github/workflows/appimage.yml
  .github/workflows/cmake.yml
  .github/workflows/cmake_qt6.yml
  .github/workflows/deploy.yml
Labels: packaging

#802 Small fixeds of SpiceLibComp
  qucs/extsimkernels/spicelibcompdialog.cpp
  qucs/projectView.cpp
  qucs/qucs_init.cpp
  qucs/spicecomponents/spicelibcomp.cpp
Labels: bug

#816 Recognize TEMP or TEMPER variable and sweep temperature
  qucs/components/param_sweep.cpp
Labels: ngspice

#838 Enable variables for blue nonlinear devices
  qucs/components/component.cpp
  qucs/components/equation.cpp
  qucs/components/param_sweep.cpp
  qucs/components/param_sweep.h
  qucs/diagrams/diagram.cpp
Labels: bug

#843 Fix ASCO running with QucsatorRF
  qucs-activefilter/CMakeLists.txt
  qucs-attenuator/CMakeLists.txt
  qucs-filter/CMakeLists.txt
  qucs-powercombining/CMakeLists.txt
  qucs-transcalc/CMakeLists.txt
  qucs/CMakeLists.txt
  qucs/dialogs/simmessage.cpp
Labels: asco

#850 Library update and pre-release fixes
  NEWS.md
  library/CMakeLists.txt
  library/Diodes_Extended.lib
  library/GeDiodes.lib
  library/MixerIC.lib
  qucs/extsimkernels/spicelibcompdialog.cpp
Labels: library

#851 Set Ngspice compatibility mode from GUI
  NEWS.md
  qucs/extsimkernels/ngspice.cpp
  qucs/extsimkernels/simsettingsdialog.cpp
  qucs/extsimkernels/simsettingsdialog.h
  qucs/extsimkernels/spicecompat.h
  qucs/settings.cpp
Labels: new feature, ngspice

#855 PWM controller library
  NEWS.md
  library/CMakeLists.txt
  library/PWM_Controller.lib
  library/qucs.blacklist
  library/xyce.blacklist
Labels: library

#845 Refactor node
  qucs/CMakeLists.txt
  qucs/conductor.h
  qucs/dialogs/sweepdialog.cpp
  qucs/element.h
  qucs/mouseactions.h
  qucs/node.cpp
  qucs/node.h
  qucs/schematic.cpp
  qucs/schematic_element.cpp
  qucs/schematic_file.cpp
  qucs/wire.h
  qucs/wirelabel.h
Labels: refactoring

#854 Replace Q3PtrList in diagram dialog
  qucs/diagrams/diagramdialog.cpp
  qucs/diagrams/diagramdialog.h
  qucs/diagrams/graph.h
Labels: refactoring

#879 Remove Schematic::textCorr
  qucs/schematic.cpp
  qucs/schematic.h
  qucs/schematic_element.cpp
Labels: refactoring
