Repository ra3xdh/qucs_s, pull requests merged in 2024-09, with the labels that each got.

#923 Substutute relative library path when inserting component in schematic
  qucs/qucs.cpp
  qucs/qucs.h
  qucs/qucslib_common.h
Labels: bug, library

#925 Improve temperature sweep
  qucs/components/bjt.cpp
  qucs/components/bjtsub.cpp
  qucs/components/component.cpp
  qucs/components/diode.cpp
  qucs/components/jfet.cpp
  qucs/components/mosfet.cpp
  qucs/components/mosfet_sub.cpp
Labels: ngspice

#932 update app icon to new one.
  contrib/InnoSetup/misc/qucs.ico
  contrib/InnoSetup/misc/qucs32x32.ico
  contrib/InnoSetup/misc/qucs64x64.ico
  contrib/InnoSetup/qucs.iss
  qucs/bitmaps/qucs.ico
Labels: packaging

#936 S-parameter viewer
  .github/workflows/cmake.yml
  .github/workflows/deploy.yml
  .gitignore
  CMakeLists.txt
  qucs-s-spar-viewer/CMakeLists.txt
  qucs-s-spar-viewer/bitmaps/big.qucs.xpm
  qucs-s-spar-viewer/bitmaps/trash.png
  qucs-s-spar-viewer/main.cpp
  qucs-s-spar-viewer/qucs-s-spar-viewer.1
  qucs-s-spar-viewer/qucs-s-spar-viewer.cpp
  qucs-s-spar-viewer/qucs-s-spar-viewer.h
  qucs-s-spar-viewer/qucs-s-spar-viewer.qrc
  qucs-s-spar-viewer/qucsattenuator.cpp
  qucs/bitmaps/qucs-s-spar-viewer.icns
  qucs/qucs.h
  qucs/qucs_actions.cpp
  qucs/qucs_init.cpp
Labels: new feature, RF, tools

#960 Fix memory leak while simulator switch
  qucs/module.cpp
  qucs/qucs.cpp
Labels: refactoring
