Repository ra3xdh/qucs_s, pull requests merged in 2024-06, with the labels that each got.

#735 Fix source components rendering quirks
  qucs/components/am_modulator.cpp
  qucs/components/ampere_ac.cpp
  qucs/components/ampere_dc.cpp
  qucs/components/ampere_noise.cpp
  qucs/components/cccs.cpp
  qucs/components/ccvs.cpp
  qucs/components/component.cpp
  qucs/components/component.h
  qucs/components/iexp.cpp
  qucs/components/ifile.cpp
  qucs/components/ipulse.cpp
  qucs/components/irect.cpp
  qucs/components/noise_ii.cpp
  qucs/components/noise_iv.cpp
  qucs/components/noise_vv.cpp
  qucs/components/pm_modulator.cpp
  qucs/components/vccs.cpp
  qucs/components/vcvs.cpp
  qucs/components/vexp.cpp
  qucs/components/vfile.cpp
  qucs/components/volt_ac.cpp
  qucs/components/volt_noise.cpp
  qucs/diagrams/diagram.cpp
  qucs/element.cpp
  qucs/element.h
  qucs/misc.cpp
  qucs/misc.h
  qucs/paintings/graphictext.cpp
  qucs/spicecomponents/S4Q_I.cpp
  qucs/spicecomponents/S4Q_Ieqndef.cpp
  qucs/spicecomponents/eNL.cpp
  qucs/spicecomponents/gNL.cpp
  qucs/spicecomponents/iAmpMod.cpp
  qucs/spicecomponents/iPWL.cpp
  qucs/spicecomponents/iTRNOISE.cpp
  qucs/spicecomponents/isffm.cpp
  qucs/spicecomponents/src_eqndef.cpp
  qucs/spicecomponents/vAmpMod.cpp
  qucs/spicecomponents/vPWL.cpp
  qucs/spicecomponents/vTRNOISE.cpp
  qucs/spicecomponents/vTRRANDOM.cpp
  qucs/spicecomponents/vsffm.cpp
Labels: refactoring

#737 Add explicit deprecation warning on attaching symbol to VA-file
  qucs/qucs.cpp
Labels: documentation

#767 Add Varactor_RF and PIN diode libraries
  library/CMakeLists.txt
  library/PIN_Diodes.lib
  library/Varactor.lib
  library/Varactor_RF.lib
Labels: library

#783 Refactor simulation components
  qucs/components/CMakeLists.txt
  qucs/components/ac_sim.cpp
  qucs/components/ac_sim.h
  qucs/components/component.cpp
  qucs/components/component.h
  qucs/components/dc_sim.cpp
  qucs/components/dc_sim.h
  qucs/components/digi_sim.cpp
  qucs/components/digi_sim.h
  qucs/components/etr_sim.cpp
  qucs/components/etr_sim.h
  qucs/components/hb_sim.cpp
  qucs/components/hb_sim.h
  qucs/components/opt_sim.cpp
  qucs/components/opt_sim.h
  qucs/components/param_sweep.cpp
  qucs/components/param_sweep.h
  qucs/components/simulation.cpp
  qucs/components/simulation.h
  qucs/components/sp_sim.cpp
  qucs/components/sp_sim.h
  qucs/components/tr_sim.cpp
  qucs/components/tr_sim.h
  qucs/spicecomponents/sp_customsim.cpp
  qucs/spicecomponents/sp_customsim.h
  qucs/spicecomponents/sp_disto.cpp
  qucs/spicecomponents/sp_disto.h
  qucs/spicecomponents/sp_fourier.cpp
  qucs/spicecomponents/sp_fourier.h
  qucs/spicecomponents/sp_noise.cpp
  qucs/spicecomponents/sp_noise.h
  qucs/spicecomponents/sp_pz.cpp
  qucs/spicecomponents/sp_pz.h
  qucs/spicecomponents/sp_sens.cpp
  qucs/spicecomponents/sp_sens.h
  qucs/spicecomponents/sp_sens_ac.cpp
  qucs/spicecomponents/sp_sens_ac.h
  qucs/spicecomponents/sp_sens_tr_xyce.cpp
  qucs/spicecomponents/sp_sens_tr_xyce.h
  qucs/spicecomponents/sp_sens_xyce.cpp
  qucs/spicecomponents/sp_sens_xyce.h
  qucs/spicecomponents/sp_spectrum.cpp
  qucs/spicecomponents/sp_spectrum.h
  qucs/spicecomponents/xyce_script.cpp
  qucs/spicecomponents/xyce_script.h
Labels: refactoring
