Repository ra3xdh/qucs_s, pull requests merged in 2024-02, with the labels that each got.

#520 Fix #432 library issues
  qucs/dialogs/librarydialog.cpp
Labels: library

#521 Refactor schematic's grid-drawing
  qucs/schematic.cpp
  qucs/schematic.h
Labels: refactoring

#528 Fix crashes
  qucs/schematic.cpp
  qucs/schematic_file.cpp
Labels: bug

#524 Fix poor grid appearence on HiDPI displays
  qucs/schematic.cpp
Labels: refactoring

#530 Fix selection of wirelabel
  CMakeLists.txt
  qucs/misc.cpp
  qucs/schematic_element.cpp
Labels: bug

#529 Persist geometry of ComponentDialog
  qucs/components/componentdialog.cpp
Labels: gui

#526 Fix grid slip on wide displays
  qucs/schematic.cpp
Labels: refactoring

#525 Extract THD % from FOUR simulation
  examples/ngspice/audio_amp_thd.sch
  qucs/extsimkernels/abstractspicekernel.cpp
  qucs/extsimkernels/abstractspicekernel.h
  qucs/extsimkernels/ngspice.cpp
Labels: ngspice

#534 Implement mouse wheel zoom of text documents
  qucs/qucs.cpp
  qucs/textdoc.cpp
  qucs/textdoc.h
Labels: new feature

#535 Add loudspeaker library
  library/CMakeLists.txt
  library/Loudspeaker.lib
Labels: library

#538 Added thermistor library
  library/CMakeLists.txt
  library/Thermistor.lib
Labels: library

#540 Fix crash on schematic close
  qucs/qucs.cpp
  qucs/schematic.cpp
Labels: bug

#543 Update qucs_run_hdl.bat to use GHDL on Windows
  qucs/qucs_run_hdl.bat
Labels: digital

#564 Add RLCG device support for Ngspice
  qucs/components/rlcg.cpp
  qucs/components/rlcg.h
Labels: RF

#566 Update NEWS.md
  NEWS.md
  debian/changelog
Labels: packaging

#580 Update Russian translation
  translations/qucs_ar.ts
  translations/qucs_ca.ts
  translations/qucs_cs.ts
  translations/qucs_de.ts
  translations/qucs_en.ts
  translations/qucs_es.ts
  translations/qucs_fr.ts
  translations/qucs_he.ts
  translations/qucs_hu.ts
  translations/qucs_it.ts
  translations/qucs_ja.ts
  translations/qucs_kk.ts
  translations/qucs_pl.ts
  translations/qucs_pt_BR.ts
  translations/qucs_pt_PT.ts
  translations/qucs_ro.ts
  translations/qucs_ru.ts
  translations/qucs_sv.ts
  translations/qucs_tr.ts
  translations/qucs_uk.ts
  translations/qucs_zh_CN.ts
Labels: localization

#582 Add Monte Carlo analysis template for ngspice
  examples/templates_ngspice/Monte_Carlo.sch
Labels: documentation

#585 Add contributing guidelines
  CONTRIBUTING.md
Labels: documentation

#584 Refine MVC
  qucs/CMakeLists.txt
  qucs/schematic.cpp
  qucs/schematic.h
  qucs/schematic_render.cpp
Labels: refactoring

#597 DC PZ SENS SENS_AC equations
  qucs/components/componentdialog.cpp
  qucs/components/dc_sim.cpp
  qucs/extsimkernels/ngspice.cpp
Labels: ngspice

#610 Add loop and spiral inductors
  qucs/components/CMakeLists.txt
  qucs/components/circularloop.cpp
  qucs/components/circularloop.h
  qucs/components/components.h
  qucs/components/spiralinductor.cpp
  qucs/components/spiralinductor.h
  qucs/module.cpp
  qucs/spicecomponents/LTL_SPICE.cpp
Labels: RF
