Repository ra3xdh/qucs_s, pull requests merged in 2024-01, with the labels that each got.

#428 Fix ideal.lib; fixes #258
  library/Ideal.lib
Labels: library

#412 Add support for custom prefix to dataset variables
  qucs/extsimkernels/abstractspicekernel.cpp
  qucs/extsimkernels/abstractspicekernel.h
  qucs/extsimkernels/ngspice.cpp
Labels: new feature

#467 Fix component moving
  qucs/mouseactions.cpp
  qucs/mouseactions.h
  qucs/qucs_actions.cpp
  qucs/schematic.cpp
Labels: bug

#493 Statusbar improvements
  qucs/diagrams/rectdiagram.cpp
  qucs/misc.cpp
  qucs/qucs.cpp
  qucs/qucs.h
  qucs/qucs_actions.cpp
  qucs/qucs_init.cpp
  qucs/schematic.cpp
  qucs/schematic.h
Labels: new feature

#506 Implement native Debian packaging
  debian/changelog
  debian/control
  debian/rules
  debian/source/format
  debian/watch
Labels: packaging

#510 Library and examples update
  examples/ngspice/JCM-800.sch
  examples/ngspice/Tube_amp6V6.sch
  library/Xanalogue.lib
Labels: documentation, library

#512 Add 'wait for' clause to output-only VHDL models
  qucs/components/logic_0.cpp
  qucs/components/logic_1.cpp
  qucs/components/pad2bit.cpp
  qucs/components/pad3bit.cpp
  qucs/components/pad4bit.cpp
Labels: digital

#515 Fix build error for MXE
  qucs/components/component.cpp
  qucs/schematic.cpp
Labels: windows

#517 Update SpiceOpamp.lib
  library/SpiceOpamp.lib
Labels: library
