Repository ra3xdh/qucs_s, pull requests merged in 2024-08, with the labels that each got.

#880 QucsAttenuator: Ensure Zout=Zin in QW and Lpad attenuators
  qucs-attenuator/qucsattenuator.cpp
Labels: bug, RF, tools

#881 Fix segfault when component is placed over a wire
  qucs/node.h
  qucs/schematic_element.cpp
Labels: bug, refactoring

#844 Get rid of MouseActions::drawn
  qucs/mouseactions.cpp
  qucs/mouseactions.h
  qucs/paintings/arrow.cpp
  qucs/paintings/arrow.h
  qucs/paintings/ellipse.cpp
  qucs/paintings/ellipse.h
  qucs/paintings/ellipsearc.cpp
  qucs/paintings/ellipsearc.h
  qucs/paintings/graphicline.cpp
  qucs/paintings/graphicline.h
  qucs/paintings/graphictext.cpp
  qucs/paintings/graphictext.h
  qucs/paintings/painting.h
  qucs/paintings/portsymbol.cpp
  qucs/paintings/portsymbol.h
  qucs/paintings/rectangle.cpp
  qucs/paintings/rectangle.h
  qucs/qucs.cpp
  qucs/qucs_actions.cpp
  qucs/schematic.cpp
  qucs/schematic_render.cpp
Labels: refactoring

#878 Refactor Schematic::selectElements
  qucs/mouseactions.cpp
  qucs/qucs_actions.cpp
  qucs/schematic.h
  qucs/schematic_element.cpp
Labels: refactoring

#901 Upload install scripts
  contrib/InnoSetup/misc/big.qucs.ico
  contrib/InnoSetup/misc/docsite.url
  contrib/InnoSetup/misc/gpl.rtf
  contrib/InnoSetup/misc/mingw.url
  contrib/InnoSetup/misc/qucs32x32.ico
  contrib/InnoSetup/misc/qucs64x64.ico
  contrib/InnoSetup/misc/website.url
  contrib/InnoSetup/qucs.iss
  contrib/gentoo/qucs_s.ebuild
Labels: packaging
