Repository ra3xdh/qucs_s, pull requests merged in 2024-10, with the labels that each got.

#991 Spar viewer: Fixes and New Features
  qucs-s-spar-viewer/main.cpp
  qucs-s-spar-viewer/qucs-s-spar-viewer.cpp
  qucs-s-spar-viewer/qucs-s-spar-viewer.h
Labels: new feature, RF

#990 Fix unnecessary setPen before draw_resize_handle
  qucs/diagrams/tabdiagram.cpp
  qucs/misc.cpp
  qucs/paintings/ellipse.cpp
  qucs/paintings/ellipsearc.cpp
Labels: refactoring

#995 Fix missing text in schematic after upgrading to Qt-6.8.0
  qucs/components/component.cpp
  qucs/components/simulation.cpp
  qucs/diagrams/marker.cpp
  qucs/diagrams/tabdiagram.cpp
  qucs/diagrams/timingdiagram.cpp
  qucs/element.cpp
  qucs/misc.cpp
  qucs/paintings/id_text.cpp
  qucs/paintings/portsymbol.cpp
  qucs/schematic.cpp
  qucs/symbolwidget.cpp
  qucs/wirelabel.cpp
Labels: qt6

#1021 Allow variables for diode parameters
  qucs/components/diode.cpp
Labels: bug

#1027 Schottly diode symbol fix and update library tree after creating new library
  qucs/components/diode.cpp
  qucs/qucs_actions.cpp
Labels: library
