Repository ra3xdh/qucs_s, pull requests merged in 2024-11, with the labels that each got.

#1039 Fix hardcoded version in Cauer LC filter
  qucs-filter/qf_filter.cpp
Labels: bug, filter, tools

#1056 Add MetaInfo
  contrib/CMakeLists.txt
  contrib/io.github.ra3xdh.qucs_s.metainfo.xml
Labels: packaging

#1065 Allow document grid visibilty to be toggled via menu and shortcut key
  qucs/qucs.cpp
  qucs/qucs.h
  qucs/qucs_actions.cpp
  qucs/qucs_init.cpp
Labels: new feature

#1063 Add grid color setting option
  qucs/dialogs/qucssettingsdialog.cpp
  qucs/dialogs/qucssettingsdialog.h
  qucs/schematic.cpp
  qucs/schematic.h
  qucs/settings.cpp
Labels: new feature

#1054 New Component Properties dialog
  qucs/components/componentdialog.cpp
  qucs/components/componentdialog.h
Labels: new feature

#1094 update turkish translate.
  qucs/dialogs/aboutdialog.cpp
  translations/qucs_tr.ts
Labels: localization

#1091 CI improvements
  .github/workflows/cmake.yml
  .github/workflows/deploy.yml
  qucs-activefilter/CMakeLists.txt
  qucs-attenuator/CMakeLists.txt
  qucs-filter/CMakeLists.txt
  qucs-powercombining/CMakeLists.txt
  qucs-s-spar-viewer/CMakeLists.txt
  qucs-transcalc/CMakeLists.txt
  qucs/CMakeLists.txt
Labels: CI

#1103 CI improvements.
  .github/workflows/deploy.yml
Labels: CI
