Repository ra3xdh/qucs_s, pull requests merged in 2025-05, with the labels that each got.

#1339 S-parameter viewer: Fixes
  qucs-s-spar-viewer/polarplotwidget.cpp
  qucs-s-spar-viewer/polarplotwidget.h
  qucs-s-spar-viewer/qucs-s-spar-viewer.cpp
  qucs-s-spar-viewer/qucs-s-spar-viewer.h
  qucs-s-spar-viewer/rectangularplotwidget.cpp
  qucs-s-spar-viewer/rectangularplotwidget.h
  qucs-s-spar-viewer/smithchartwidget.cpp
  qucs-s-spar-viewer/smithchartwidget.h
Labels: RF, tools

#1337 A bit of schematic refactoring
  qucs/qucsdoc.h
  qucs/schematic.cpp
  qucs/schematic.h
  qucs/schematic_render.cpp
  qucs/textdoc.cpp
  qucs/textdoc.h
Labels: refactoring

#1346 Project view: Open files with the system default program
  qucs-s-spar-viewer/main.cpp
  qucs-s-spar-viewer/qucs-s-spar-viewer.cpp
  qucs-s-spar-viewer/qucs-s-spar-viewer.h
  qucs/qucs.cpp
Labels: new feature, linux

#1348 Fix crash when deleting label after wire merge
  qucs/schematic_element.cpp
Labels: bug

#1336 Fix for issues 1223 regarding CDL netlisting
  qucs/dialogs/librarydialog.cpp
  qucs/extsimkernels/CMakeLists.txt
  qucs/extsimkernels/CdlNetlistWriter.cpp
  qucs/extsimkernels/CdlNetlistWriter.h
  qucs/extsimkernels/CdlSettingsDialog.cpp
  qucs/extsimkernels/CdlSettingsDialog.h
  qucs/extsimkernels/abstractspicekernel.cpp
  qucs/extsimkernels/abstractspicekernel.h
  qucs/main.cpp
  qucs/main.h
  qucs/qucs.cpp
  qucs/qucs.h
  qucs/qucs_init.cpp
  qucs/schematic_file.cpp
Labels: IHP

#1362 Add a context menu to documents tabs
  qucs/qucs.cpp
  qucs/qucs.h
  qucs/qucs_init.cpp
Labels: new feature

#1364 Allow free editing for NODESET
  qucs/components/componentdialog.cpp
Labels: bug

#1365 improve CI.
  .github/workflows/deploy.yml
Labels: CI

#1366 Fix missing DLLs (CI)
  .github/workflows/deploy.yml
Labels: CI

#1356 Refactor property
  qucs/components/CMakeLists.txt
  qucs/components/capq.cpp
  qucs/components/cccs.cpp
  qucs/components/ccvs.cpp
  qucs/components/component.cpp
  qucs/components/component.h
  qucs/components/componentdialog.cpp
  qucs/components/indq.cpp
  qucs/components/property.cpp
  qucs/components/property.h
  qucs/components/resistor.cpp
  qucs/components/switch.cpp
  qucs/components/tr_sim.cpp
  qucs/components/vcvs.cpp
  qucs/element.cpp
  qucs/element.h
  qucs/spicecomponents/LTL_SPICE.cpp
Labels: new feature, refactoring

#1370 Fix scalars plotting
  qucs/extsimkernels/abstractspicekernel.cpp
  qucs/extsimkernels/abstractspicekernel.h
Labels: bug

#1371 Refactor Schematic::activateCompsWithinRect
  qucs/components/component.cpp
  qucs/components/component.h
  qucs/schematic.h
  qucs/schematic_element.cpp
Labels: refactoring

#1374 SPICE models for Qucsator devices
  library/spicelibrary/coax.cir
  qucs/components/coaxialline.cpp
  qucs/components/coaxialline.h
  qucs/components/gyrator.cpp
  qucs/components/tline.cpp
  qucs/components/tline.h
  qucs/components/tline_4port.cpp
  qucs/components/tline_4port.h
Labels: new feature, ngspice, RF

#1378 Open multiple schematics from the Content View tab
  qucs/projectView.cpp
  qucs/projectView.h
  qucs/qucs.cpp
  qucs/qucs.h
Labels: new feature
