Repository ra3xdh/qucs_s, pull requests merged in 2025-06, with the labels that each got.

#1389 Fix crash when moving a wirelabel
  qucs/schematic_element.cpp
Labels: bug

#1391 Fix wrong marker root position
  qucs/diagrams/marker.cpp
Labels: bug

#1393 Refactor Marker::initText()
  qucs/diagrams/marker.cpp
Labels: refactoring

#1404 Small refactorings
  qucs/components/component.cpp
  qucs/components/component.h
  qucs/components/param_sweep.cpp
  qucs/components/sp_sim.cpp
  qucs/diagrams/diagram.cpp
  qucs/diagrams/graph.h
  qucs/diagrams/marker.cpp
  qucs/diagrams/rect3ddiagram.cpp
  qucs/diagrams/tabdiagram.cpp
  qucs/diagrams/truthdiagram.cpp
  qucs/dialogs/librarydialog.cpp
  qucs/dialogs/matchdialog.cpp
  qucs/dialogs/simmessage.cpp
  qucs/dialogs/sweepdialog.cpp
  qucs/dialogs/sweepdialog.h
  qucs/extsimkernels/abstractspicekernel.cpp
  qucs/extsimkernels/xyce.cpp
  qucs/extsimkernels/xyce.h
  qucs/main.cpp
  qucs/mouseactions.cpp
  qucs/node.cpp
  qucs/qucs.cpp
  qucs/qucs_actions.cpp
  qucs/schematic.cpp
  qucs/schematic_element.cpp
  qucs/schematic_file.cpp
  qucs/wire.cpp
Labels: refactoring

#1403 Image component
  qucs/bitmaps/svg/ImagePainting.svg
  qucs/module.cpp
  qucs/paintings/CMakeLists.txt
  qucs/paintings/imagepainting.cpp
  qucs/paintings/imagepainting.h
  qucs/paintings/paintings.h
  qucs/qucs.qrc
  qucs/schematic.cpp
  qucs/schematic.h
  qucs/schematic_element.cpp
  qucs/schematic_file.cpp
Labels: new feature
