Repository ra3xdh/qucs_s, pull requests merged in 2025-02, with the labels that each got.

#1226 Update NEWS and VERSION before release
  NEWS.md
  VERSION
Labels: packaging

#1201 Introduce optional netlisting to console
  qucs/components/component.cpp
  qucs/components/component.h
  qucs/components/equation.cpp
  qucs/components/equation.h
  qucs/components/iprobe.cpp
  qucs/components/iprobe.h
  qucs/components/vprobe.cpp
  qucs/components/vprobe.h
  qucs/extsimkernels/CdlNetlistWriter.cpp
  qucs/extsimkernels/externsimdialog.cpp
  qucs/extsimkernels/externsimdialog.h
  qucs/extsimkernels/ngspice.cpp
  qucs/extsimkernels/ngspice.h
  qucs/extsimkernels/xyce.cpp
  qucs/extsimkernels/xyce.h
  qucs/main.cpp
  qucs/qucs.cpp
  qucs/qucs.h
  qucs/qucs_init.cpp
  qucs/spicecomponents/incl_script.cpp
  qucs/spicecomponents/incl_script.h
  qucs/spicecomponents/sp_csparameter.cpp
  qucs/spicecomponents/sp_csparameter.h
  qucs/spicecomponents/sp_func.cpp
  qucs/spicecomponents/sp_func.h
  qucs/spicecomponents/sp_globalpar.cpp
  qucs/spicecomponents/sp_globalpar.h
  qucs/spicecomponents/sp_ic.cpp
  qucs/spicecomponents/sp_ic.h
  qucs/spicecomponents/sp_nodeset.cpp
  qucs/spicecomponents/sp_nodeset.h
  qucs/spicecomponents/sp_options.cpp
  qucs/spicecomponents/sp_options.h
  qucs/spicecomponents/sp_parameter.cpp
  qucs/spicecomponents/sp_parameter.h
Labels: refactoring, IHP

#1232 Add two new wire forms
  qucs/CMakeLists.txt
  qucs/mouseactions.cpp
  qucs/schematic.h
  qucs/schematic_element.cpp
  qucs/wire_planner.cpp
  qucs/wire_planner.h
Labels: new feature

#1235 Refactor Schematic::sizeOfSelection() and its usages
  qucs/imagewriter.cpp
  qucs/schematic.cpp
  qucs/schematic.h
  qucs/schematic_element.cpp
Labels: refactoring

#1236 Refactor Schematic::setComponentNumber()
  qucs/schematic_element.cpp
Labels: refactoring

#1239 update qt and ngspice
  .github/workflows/deploy.yml
Labels: packaging, CI

#1237 Replace some Q3PtrList usages with QList
  qucs/mouseactions.cpp
  qucs/mouseactions.h
  qucs/qucs_actions.cpp
  qucs/schematic.cpp
  qucs/schematic.h
  qucs/schematic_element.cpp
  qucs/schematic_file.cpp
Labels: refactoring

#1240 Library update
  NEWS.md
  library/Analog.lib
  library/CMakeLists.txt
  library/RC.lib
  qucs/dialogs/aboutdialog.cpp
  qucs/dialogs/aboutdialog.h
Labels: library

#1246 Update Russian translation
  qucs/dialogs/qucssettingsdialog.cpp
  qucs/dialogs/tuner.cpp
  qucs/qucs_init.cpp
  translations/qucs_ar.ts
  translations/qucs_ca.ts
  translations/qucs_cs.ts
  translations/qucs_de.ts
  translations/qucs_en.ts
  translations/qucs_es.ts
  translations/qucs_fr.ts
  translations/qucs_he.ts
  translations/qucs_hu.ts
  translations/qucs_it.ts
  translations/qucs_ja.ts
  translations/qucs_kk.ts
  translations/qucs_pl.ts
  translations/qucs_pt_BR.ts
  translations/qucs_pt_PT.ts
  translations/qucs_ro.ts
  translations/qucs_ru.ts
  translations/qucs_sv.ts
  translations/qucs_tr.ts
  translations/qucs_uk.ts
  translations/qucs_zh_CN.ts
Labels: localization

#1249 Update MetaInfo
  contrib/io.github.ra3xdh.qucs_s.metainfo.xml
Labels: packaging

#1252 Update Gentoo ebuild
  contrib/gentoo/README.md
  contrib/gentoo/metadata/layout.conf
  contrib/gentoo/profiles/repo_name
  contrib/gentoo/qucs_s.ebuild
  contrib/gentoo/sci-electronics/qucs_s/Manifest
  contrib/gentoo/sci-electronics/qucs_s/metadata.xml
  contrib/gentoo/sci-electronics/qucs_s/qucs_s-24.4.1.ebuild
  contrib/gentoo/sci-electronics/qucs_s/qucs_s-25.1.0.ebuild
  contrib/gentoo/sci-electronics/qucs_s/qucs_s-9999.ebuild
Labels: packaging
