Repository ra3xdh/qucs_s, pull requests merged in 2025-01, with the labels that each got.

#1180 Power amplifier THD vs. output voltage RMS ngspice template
  examples/templates_ngspice/PwrAmpTHD.sch
Labels: ngspice, documentation

#1182 Digital libraries
  library/CMakeLists.txt
  library/Digital_CD4000.lib
  library/Digital_HC.lib
  library/Digital_LV.lib
  library/qucs.blacklist
  library/xyce.blacklist
Labels: library

#1181 Deprecate Qt5
  .github/workflows/deploy.yml
  CMakeLists.txt
  qucs-activefilter/CMakeLists.txt
  qucs-attenuator/CMakeLists.txt
  qucs-filter/CMakeLists.txt
  qucs-powercombining/CMakeLists.txt
  qucs-s-spar-viewer/CMakeLists.txt
  qucs-s-spar-viewer/qucs-s-spar-viewer.h
  qucs-transcalc/CMakeLists.txt
  qucs/CMakeLists.txt
  qucs/components/CMakeLists.txt
  qucs/diagrams/CMakeLists.txt
  qucs/dialogs/CMakeLists.txt
  qucs/extsimkernels/CMakeLists.txt
  qucs/extsimkernels/abstractspicekernel.cpp
  qucs/extsimkernels/ngspice.cpp
  qucs/extsimkernels/qucs2spice.cpp
  qucs/extsimkernels/s2spice.cpp
  qucs/extsimkernels/spicecompat.cpp
  qucs/main.cpp
  qucs/misc.h
  qucs/paintings/CMakeLists.txt
  qucs/qt3_compat/CMakeLists.txt
  qucs/qt3_compat/q3scrollview.cpp
  qucs/qucs.cpp
  qucs/schematic.cpp
  qucs/schematic_file.cpp
  qucs/spicecomponents/CMakeLists.txt
  translations/CMakeLists.txt
Labels: qt5, qt6, refactoring

#1196 Fix compiler warnings
  qucs-activefilter/main.cpp
  qucs-attenuator/main.cpp
  qucs-filter/main.cpp
  qucs-powercombining/main.cpp
  qucs-s-spar-viewer/main.cpp
  qucs-transcalc/main.cpp
  qucs/main.cpp
Labels: refactoring

#1197 Allow passing parameters for SPICE subcircuits
  library/Thyristor.lib
  qucs/components/spicedialog.cpp
  qucs/components/spicedialog.h
  qucs/components/spicefile.cpp
Labels: new feature, ngspice

#1218 Add offset and Td parameters for AC current source
  qucs/components/ampere_ac.cpp
Labels: new feature
