Repository ra3xdh/qucs_s, pull requests merged in 2025-09, with the labels that each got.

#1461 Update QT and NGSpice versions in CI
  .github/workflows/deploy.yml
Labels: CI

#1462 Update NGspice URL
  .github/workflows/deploy.yml
Labels: ngspice, CI

#1464 Russian translation
  translations/qucs_ru.ts
Labels: localization
